### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by DmytroLitvinov** [titulebolide/crypto-bot#4]
Hi there,
I have cloned project at VPS server and created snapshot of account and  run next command:
`python main.py --output print` and I received next error at console:

```
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    main()
  File "/home/manager/binance-trade-bot/binance-trade-bot/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/manager/binance-trade-bot/binance-trade-bot/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/manager/binance-trade-bot/binance-trade-bot/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/manager/binance-trade-bot/binance-trade-bot/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 49, in main
    figname = bot.crypto.plot_symbol(reports, plot_symbol)
  File "/home/manager/binance-trade-bot/binance-report-bot/bot/crypto.py", line 92, in plot_symbol
    Y.append(report['total_usdt']/ticker)
ZeroDivisionError: float division by zero
```

**Comment by titulebolide** [comment]
Hey!
Could you paste your conf.py file?
Please censor your binance keys

**Comment by DmytroLitvinov** [comment]
Here it is:
```
COINS = ["BTC","ADA","ATOM","BAT","BTT","CAKE","DASH","EOS","ETC","ICX","IOTA",>
CURRENCY = "USB" #Or USD
CURRENCY_SYMBOL = "$"
RICH_PRINTING = True
```

**Comment by titulebolide** [comment]
You have your currency set at "USB", set it at "USD". That's why it can't find your price. Then delete the /db/crypto.npy file and run again

**Comment by DmytroLitvinov** [comment]
Oops.
Sorry.. Seems like I am not attentive.)
But thanks for supporting :)

**Comment by titulebolide** [comment]
No problem, thanks for the PRs by the way!
