### ISSUE TITLE
KeyError: 'NFT'

### ISSUE THREAD

**Issue by titulebolide** [titulebolide/crypto-bot#8]
`python -m brb snapshot`
leads to 
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/bot/crypto/brb/__main__.py", line 92, in <module>
    cli()
  File "/srv/bot/crypto/venv/lib/python3.7/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/srv/bot/crypto/venv/lib/python3.7/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/srv/bot/crypto/venv/lib/python3.7/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/bot/crypto/venv/lib/python3.7/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/bot/crypto/venv/lib/python3.7/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/srv/bot/crypto/brb/__main__.py", line 29, in snapshot
    crypto_report = brb.crypto.get_report()
  File "/srv/bot/crypto/brb/crypto.py", line 80, in get_report
    total_usdt += balances[symbol] * tickers[symbol]
KeyError: 'NFT'
```

**Comment by titulebolide** [comment]
fixed
